- name: AKS deployment and setup
  hosts: localhost
  vars_files:
    - variables.yml
  tasks:
    - name: Create namespace
      kubernetes.core.k8s:
        name: "cp2-ns"
        api_version: v1
        kind: Namespace
        state: present
        
    - name: 'Create PVC'
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: "{{ app_name }}-data-pvc"
            namespace: "cp2-ns"
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: "{{ storage_class }}"
            resources:
              requests:
                storage: "{{ pvc_size }}"

    - name: 'Create Deployment'
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: "{{ app_name }}"
            labels: { app: "{{ app_name }}" }
            namespace: "cp2-ns"
          spec:
            replicas: 1
            selector:
              matchLabels: { app: "{{ app_name }}" }
            template:
              metadata:
                labels: { app: "{{ app_name }}" }
              spec:
                containers:
                  - name: "{{ app_name }}"
                    image: "{{ app_image }}"
                    ports:
                      - containerPort: 3000
                    volumeMounts:
                      - name: db
                        mountPath: "/webserver-ruby/db/"
                volumes:
                  - name: db
                    persistentVolumeClaim:
                      claimName: "{{ app_name }}-data-pvc"

    - name: 'Create LoadBalancer for app access'
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: "{{ app_name }}-lb"
            namespace: "cp2-ns"
          spec:
            type: LoadBalancer
            selector: { app: "{{ app_name }}" }
            ports:
              - port: 80
                targetPort: 3000