- name: 'Setup service VM'
  hosts: service-vm
  remote-user: azureuser
  become: true
  tasks:
    - name: 'Install podman'
      ansible.builtin.apt:
        name: podman:4.9.3+ds1-1ubuntu0.2
        state: present
        update_cache: true

    - name: 'Install podlet'
      ansible.builtin.get_url:
        url: https://github.com/containers/podlet/releases/download/v0.3.2/podlet-x86_64-unknown-linux-gnu.tar.xz
        dest: /usr/bin/
      ansible.builtin.unarchive:
        src: /usr/bin/podlet-x86_64-unknown-linux-gnu.tar.xz
        dest: /usr/bin/
      ansible.builtin.copy:
        src: /usr/bin/podlet-x86_64-unknown-linux-gnu/podlet
        dest: /usr/bin/
      ansible.builtin.file:
        path: /usr/bin/podlet-x86_64-unknown-linux-gnu.tar.xz
        state: absent

    - name: 'Setup REDIS server'
      ansible.builtin.file:
        path: /root/redis
        state: directory
      ansible.builtin.command:
        cmd: podlet --file --install --name redis podman run --detach=true -p 6379:6379 --volume /root/redis:/data redis:alpine

    - name: 'Setup Mariadb server'
      ansible.builtin.file:
        path: /root/mariadb
        state: directory
      ansible.builtin.command:
        cmd: podlet --file --install --name mariadb podman run --detach=true -p 3306:3306 --volume /root/mariadb:/var/lib/mysql mariadb:10.6


